server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  main:
    allow-bean-definition-overriding: true
  logging:
    level:
      org:
        springframework:
          web:
            filter:
              CommonsRequestLoggingFilter: DEBUG
